# -*- coding: utf-8 -*-
"""syntaxlombalagi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wURlU_0BZdGsCLfWXl-EmxdnSoGGcR5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

readdata = pd.read_csv("metadata.csv")

print("The dataset was loaded successfully\n")
print(readdata)

print("Dataset size", readdata.shape)
print("====================\n")

total_patients = len(readdata)
brugada_patients = (readdata['brugada'] == 1).sum()
healthy_patients = (readdata['brugada'] == 0).sum()

print("Total Patients :", total_patients)
print("Brugada Patients :", brugada_patients)
print("Healthy Patients :", healthy_patients)

print("Labels before adjustment:", readdata['brugada'].unique())

readdata['brugada'] = readdata['brugada'].replace({2:1})

print("Labels after adjustment:", readdata['brugada'].unique())

X = readdata[['basal_pattern','sudden_death']]
y = readdata['brugada']

print("Features used :")
X.columns

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.25,
    random_state = 58
)

print("Training samples :", len(X_train))
print("Testing samples :", len(X_test))

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = RandomForestClassifier(
    n_estimators = 200,
    criterion = 'entropy',
    random_state = 58,
    class_weight = 'balanced'
)

model.fit(X_train, y_train)

feature_importance = model.feature_importances_

importance_table = pd.DataFrame({
    "Feature": X.columns,
    "Importance": feature_importance
})

imtable = importance_table.sort_values(
    by="Importance",
    ascending=False
)

print("\nFeature Importance\n")

print(imtable)

y_prediction = model.predict(X_test)

print("Example predictions :")
print(y_prediction [:12] )

accuracy = accuracy_score(y_test, y_prediction)

print("Accuracy :")
print(accuracy)

print("Classification Report :")
print(classification_report(y_test, y_prediction))

CM = confusion_matrix(y_test, y_prediction)

labels = ["Normal", "Brugada"]

CMT = pd.DataFrame(
    CM,
    index = [f"Actual {i}" for i in labels],
    columns = [f"Predicted {i}" for i in labels]
)

precision_normal = CM[0,0] / (CM[0,0] + CM[1,0])
precision_brugada = CM[1,1] / (CM[1,1] + CM[0,1])

recall_normal = CM[0,0] / (CM[0,0] + CM[0,1])
recall_brugada = CM[1,1] / (CM[1,1] + CM[1,0])

print("Confusion Matrix\n")
print(CMT)

import seaborn as sns

plt.figure(figsize = (5,4))

sns.heatmap(CM, annot = True, fmt = "d", cmap = "Blues", xticklabels = ["Normal","Brugada"], yticklabels = ["Normal","Brugada"])

plt.title("Confusion Matrix")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

precision_normal = CM[0,0] / (CM[0,0] + CM[1,0])
precision_brugada = CM[1,1] / (CM[1,1] + CM[0,1])

recall_normal = CM[0,0] / (CM[0,0] + CM[0,1])
recall_brugada = CM[1,1] / (CM[1,1] + CM[1,0])

performance_table = pd.DataFrame({
    "Class": ["Normal","Brugada"],
    "Precision": [precision_normal, precision_brugada],
    "Recall": [recall_normal, recall_brugada]
})

print("\nPerformance Analysis\n")
print(performance_table)